# Set the status bar background to transparent (default)
set-option -g status-style bg=default

# Set the foreground (text) color to make it readable
set-option -g status-style fg=white

# This keeps the background transparent but highlights the active window text
set-window-option -g window-status-style bg=default,fg=colour244
set-window-option -g window-status-current-style bg=default,fg=white,bold

# Remove the borders between window names for a cleaner look
set-window-option -g window-status-separator "  "

# Hide the status bar by default
set -g status on

# When Ctrl+b is pressed, turn status ON, then turn it OFF after 2 seconds
# Use 'run-shell' to handle the delay in the background
# bind -n C-b set status on \; switch-client -T prefix \; run-shell -d 2 -b "sleep 2; tmux set status off"

# Manually toggle status bar visibility with Prefix + b
bind b set-option status
bind k kill-session

# Prompt for a session name, then create it (or switch to it if it exists)
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
